server:
  port: 20727

spring:
  application:
    name: academy-noface-videoo-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.academy.noface:3306/academy_noface?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: arthur
    password: arthur
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:20725/eureka/